### ISSUE TITLE
Azure Sign in not working on VSCode-insider build

### ISSUE THREAD

**Issue by scottschwab2** [microsoft/azcode#54] opened 2023-06-22 14:03 UTC
On my Mac, running vscode-insider, with the Azure Account Extension installed, when I attempt to "Sign In" I get the following message:
    "You appear to be offline. Please check your network connection."

If I use the Azure CLI, I can log into my Azure account without a problem. I have also tried the extension on my Windows 10 PC and Debian-based Linux system, with the same results.

On my Mac, I have seen a similar behavior in the normal production VSCode release when the GitHub Copilot is installed along with the Azure Account extension.

To reproduce:
1. Press F1 to bring up the vscode command window.
2. In the Window, select "Azure: Sign in"

The offline message will then appear in a popup on the lower right side.

The extension information is
Version v0.11.5
Published 9/6/2017, 13:01:27
Last released 5/16/2023, 15:02:49
Last updated 6/21/2023, 14:13:45
Identifier ms-vscode.azure-account

Running in vscode-insider
Version: 1.80.0-insider (Universal)
Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
Date: 2023-06-21T08:23:42.803Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.1.0

On my Mac
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB
macOS: Ventura 13.0

Default Browser:
Edge Version: Version 114.0.1823.55 (Official build) (x86_64)

No VPN in use.

Thanks,
Scott Schwab

**Comment by nturinski** [comment] 2023-06-27 00:03
Closing as a duplicate of https://github.com/microsoft/vscode-azure-account/issues/819. These repos are managed by the same team, so hopefully Alex can help you on the original issue.

**Closed as completed by nturinski** 2023-06-27 00:03 UTC
